# Generated by Django 5.0.6 on 2024-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_created_at', models.DateField(auto_created=True, auto_now=True)),
                ('product_name', models.CharField(max_length=244)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField()),
                ('product_quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('product_added_by', models.CharField(default='Admin', max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, auto_now=True)),
                ('username', models.CharField(max_length=244)),
                ('first_name', models.CharField(max_length=244)),
                ('last_name', models.CharField(max_length=244)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=244)),
                ('is_Active', models.BooleanField(default=False)),
            ],
        ),
    ]
